"""
Microsoft Web IQ search, exposed as an LLM-callable tool.

Design
------
The proxy does NOT search on the model's behalf and does NOT inject anything
into prompts. It only exposes one plain endpoint (``POST /v3/search/web``)
that runs a search with the server-held API key.

That endpoint is the official Microsoft Web Search v3 contract:
https://webiq.microsoft.ai/documentation/api-reference/web/

It is a transparent proxy in the strict sense -- the request body is forwarded
as the raw bytes the client sent, and the upstream status, headers and body
come back untouched. There is deliberately no parameter whitelist, no local
defaulting, no clamping and no schema validation, because every one of those
is a way for this proxy to disagree with the service it claims to be. A
parameter Microsoft adds tomorrow works here today, and an invalid request
gets the authoritative upstream error rather than an imitation of it.

The only thing that is not passed through is the API key: the client's own
``x-apikey``/``Authorization`` headers are never forwarded (that is the whole
point of key custody) and never persisted (see ``auth.redact_auth_headers``).
The single response rewrite is upstream 401/403 -> 503, because those describe
*this server's* credentials and must not be confused with this proxy rejecting
the caller's token.

The caller (the built-in chat UI, or any API client) declares ``webiq_search``
as a normal function tool, lets the model decide whether and what to search,
then executes the tool call against that endpoint and feeds the result back.
That tool schema is a prompt surface, not the API: it stays deliberately
narrow (query plus a result count) because handing a model eight knobs makes
it fill them in badly. The client is what turns those narrow arguments into a
full official request -- see ``scripts/webiq_search_demo.py``.

This keeps the LLM proxy path a pure pass-through: no hidden extra upstream
calls, no silent tool rewriting, no search failure escalating into a failed
chat request.
"""

from typing import Any, Dict, List, Optional, Tuple

import requests

TOOL_NAME = "webiq_search"

# Retired one-shot option. It used to make the proxy search on the client's
# behalf and splice results into the system prompt. It is now rejected rather
# than silently ignored, so callers cannot believe a search happened when it
# did not.
LEGACY_OPTION_KEY = "webiq_search_options"

LEGACY_OPTION_MESSAGE = (
    "'webiq_search_options' has been removed. Declare the 'webiq_search' "
    "function tool instead, and execute the model's tool calls against "
    "POST /v3/search/web."
)

TOOL_DESCRIPTION = (
    "Search the public web and return ranked passages with source URLs. "
    "Use it for facts that are recent, niche, or that you are not confident "
    "about, and cite the returned sources in your answer."
)

TOOL_PARAMETERS: Dict[str, Any] = {
    "type": "object",
    "properties": {
        "query": {
            "type": "string",
            "description": (
                "A focused search-engine query (keywords, not a full "
                "sentence). Resolve pronouns from the conversation first."
            ),
        },
        "max_results": {
            "type": "integer",
            "description": "How many results to return (1-10).",
            "minimum": 1,
            "maximum": 10,
        },  # kept snake_case: this is the model-facing tool, not the HTTP API
    },
    "required": ["query"],
    "additionalProperties": False,
}

# The endpoint the Web Search v3 specification defines, used unless config.yaml
# overrides it via webiq_endpoint (for a mock, a recording proxy, or a regional
# deployment), matching the github_api_base_url/copilot_api_base_url overrides
# elsewhere in this project.
ENDPOINT = "https://api.microsoft.ai/v3/search/web"

# Response headers that must not be copied from upstream to the client.
#
# * Hop-by-hop headers are forbidden for WSGI applications by PEP 3333
#   (waitress answers 500 if one appears) and describe the upstream connection,
#   not this one.
# * Content-Length/Content-Encoding describe a body framing that Flask
#   recomputes for its own response.
# * Date and Server are generated by this server. Copying them too makes the
#   WSGI layer emit a comma-joined "Date: <ours>, <upstream's>", which is both
#   wrong and unparseable.
# * Alt-Svc and Strict-Transport-Security are claims about *upstream's* origin
#   ("this origin also speaks h3 on port N", "this origin is HTTPS-only").
#   Re-emitted here they become claims about this proxy's origin, which are not
#   true and which a browser would act on.
#
# Everything else survives, so Retry-After and the x-ms-* diagnostics reach the
# caller.
DROPPED_RESPONSE_HEADERS = frozenset({
    "connection", "keep-alive", "proxy-authenticate", "proxy-authorization",
    "te", "trailer", "trailers", "transfer-encoding", "upgrade",
    "content-length", "content-encoding",
    "date", "server",
    "alt-svc", "strict-transport-security",
})


class WebIQError(RuntimeError):
    """A safe-to-return Web IQ failure carrying an HTTP status code.

    Raised only when there is no upstream response to pass through: this
    server is unconfigured, the connection failed, or upstream rejected this
    server's key. Everything else is returned verbatim, not raised.
    """

    def __init__(self, message: str, status_code: int = 502):
        super().__init__(message)
        self.status_code = status_code


def pop_legacy_option(payload: Dict) -> bool:
    """Strip the retired option from a payload in place.

    Always removes the key so it can never be forwarded upstream as an unknown
    parameter. Returns True when the caller actually asked for a search, so the
    route can answer with a migration error instead of quietly dropping it.
    """
    if not isinstance(payload, dict) or LEGACY_OPTION_KEY not in payload:
        return False
    option = payload.pop(LEGACY_OPTION_KEY)
    if isinstance(option, dict):
        return bool(option.get("enabled", True))
    return bool(option)


def is_configured(settings: Any) -> bool:
    """Whether Web IQ is enabled and has a key."""
    return bool(getattr(settings, "enable_webiq_search", False)
                and getattr(settings, "webiq_api_key", ""))


def tool_definition(api_style: str) -> Dict[str, Any]:
    """Return the webiq_search tool schema in Chat or Responses shape."""
    if api_style == "responses":
        return {
            "type": "function",
            "name": TOOL_NAME,
            "description": TOOL_DESCRIPTION,
            "parameters": TOOL_PARAMETERS,
        }
    return {
        "type": "function",
        "function": {
            "name": TOOL_NAME,
            "description": TOOL_DESCRIPTION,
            "parameters": TOOL_PARAMETERS,
        },
    }


def endpoint_for(settings: Any) -> str:
    """The upstream URL to call: the configured override, or the spec one."""
    return getattr(settings, "webiq_endpoint", "") or ENDPOINT


def passthrough_headers(headers: Any) -> List[Tuple[str, str]]:
    """Upstream response headers that are safe to hand back to the client.

    Everything survives except the connection-, framing- and origin-scoped ones
    listed in DROPPED_RESPONSE_HEADERS, so ``Retry-After`` on a 429 -- the one
    header a client needs in order to back off correctly against a shared paid
    key -- reaches the caller.
    """
    if not headers:
        return []
    return [(name, value) for name, value in headers.items()
            if name.lower() not in DROPPED_RESPONSE_HEADERS]


def search(
    body: bytes,
    settings: Any,
    *,
    content_type: str = "application/json",
) -> requests.Response:
    """Forward one Web Search v3 request and return the raw upstream response.

    ``body`` is handed over as received; this function never parses, validates,
    defaults or rewrites it. The caller gets the ``requests.Response`` so it
    can pass status, headers and content through verbatim.

    Raises WebIQError only when there is nothing to pass through: not
    configured, connection failed, or upstream rejected this server's key.
    """
    if not is_configured(settings):
        raise WebIQError("Microsoft Web IQ is not configured on this server.", 503)

    try:
        response = requests.post(
            endpoint_for(settings),
            headers={
                # The client's own x-apikey/Authorization are deliberately not
                # forwarded: this server's key is the only one that is used.
                # Host is not set here either; urllib3 derives it from the URL.
                "x-apikey": settings.webiq_api_key,
                "content-type": content_type or "application/json",
            },
            data=body,
            timeout=settings.webiq_timeout,
        )
    except (requests.exceptions.Timeout, requests.exceptions.ConnectionError) as exc:
        raise WebIQError(f"Web IQ connection failed: {type(exc).__name__}", 504) from exc
    except requests.RequestException as exc:
        raise WebIQError(f"Web IQ request failed: {type(exc).__name__}") from exc

    if response.status_code in (401, 403):
        detail = (response.text or "").strip()
        if len(detail) > 500:
            detail = detail[:500] + "..."
        raise WebIQError(
            "Web IQ rejected this server's API key "
            f"(upstream HTTP {response.status_code}). "
            "Check webiq_api_key in config.yaml."
            + (f" Upstream said: {detail}" if detail else ""),
            503,
        )

    return response


def result_count(body: Any) -> Optional[int]:
    """Number of webResults in a parsed response body, or None if unknown.

    Used for the log line and nothing else; the response itself is never
    inspected on its way to the client.
    """
    if not isinstance(body, dict):
        return None
    results = body.get("webResults")
    return len(results) if isinstance(results, list) else None
